class Cart(object):
    edit = 'a[class="action action-edit"]'
    quantity_field = 'input.input-text.qty'
    delete_item = 'a[class="action action-delete"]'
    is_upgraded = 'span[class="counter qty"]'
    subtotal = 'span[class="price-wrapper"]>span'
    quantity = 'input[class="item-qty cart-item-qty"]'
    update = 'button[class="update-cart-item"]'
    number_of_items = 'div.items-total>span.count'
    delete = 'a[class="action delete"]'
    confirm = 'button[class="action-primary action-accept"]'
    proceed_to_checkout_button = 'ul[class="checkout methods items checkout-methods-items"]>li>button'
    product_name = 'strong.product-item-name>a'
